### ISSUE TITLE
"Send via AirPlay" stops after a while?

### ISSUE THREAD

**Issue by jonchui** [hoyois/safariextensions#6]
Love the inclusion of Airplay to clicktoflash and clicktoplugin, but why does it stop after a few seconds of playing?

I'm on 4.2.2 apple tv

cheers

**Comment by hoyois** [comment]
Do you mean 4.4 instead of 4.2? If so: http://hoyois.github.com/safariextensions/clicktoplugin/support.xhtml#broken_apple_tv
In any case, this feature has only been tested with 4.3 and 4.4, and it only works properly with the former.

**Comment by jonchui** [comment]
Yeah that's the issue

Do you have any idea what the problem is?

Pardon the spelling mistakes. Siri's still learning.

On 2012-01-02, at 7:21 PM, Marc Hoyois
reply@reply.github.com
wrote:

**Comment by hoyois** [comment]
Not really. I know that it's not an intentional change, so it must be an unforeseen side effect of something else. It may simply be a bug that the Apple TV cannot download something for more than a few seconds. Depending on your connection, you'll get shorter or longer playack. I guess this could be tested by comparing the playback times for low-res and high-res videos.
